version: '3.9'

services:
  big-agi:
    image: ghcr.io/enricoros/big-agi:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: [ "next", "start", "-p", "4000" ]

  nginx:
    image: nginx:alpine
    ports:
      - "4001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - big-agi
